#!/bin/bash
set -xe

# Configure
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup
go get -u -v golang.org/x/net/proxy
go install \
	github.com/dvyukov/go-fuzz/go-fuzz \
	github.com/dvyukov/go-fuzz/go-fuzz-build \
	github.com/dvyukov/go-fuzz/go-fuzz-dep \
	github.com/fuzzitdev/fuzzit/v2
$DIR/fuzz-gopath
export GOPATH=$DIR/gopath
export GO111MODULES=off

# Fuzz
go-fuzz-build -libfuzzer -o fuzzer.a .
clang -fsanitize=fuzzer fuzzer.a -o fuzzer
fuzzit create job --type ${1} skaffold/parse-config fuzzer
